### ISSUE TITLE
Questions when creating a source image from a COCO dataset

### ISSUE THREAD

**Issue by olccihyeon** [OSU-NLP-Group/MagicBrush#11]
The images in the coco dataset vary widely in size. However, the source image of magicbrush has a size of (500,500). 

How did you preprocess the images in the coco dataset and what is the procedure?

Thank you

**Comment by drogozhang** [comment]
Hi, thanks for your interest in our work.
 
Here is the code we used for automatically image cropping: https://github.com/haofanwang/cropimage
Hope it helps.
 
Best,
Kai
