### ISSUE TITLE
Bug fix: evaluation script

### ISSUE THREAD

**Issue by BennoKrojer** [OSU-NLP-Group/MagicBrush#13]
Hi Kai,

I just found a small bug in `image_eval.py` line 144 (https://github.com/OSU-NLP-Group/MagicBrush/blob/7fea960a2a98542b9721fb07a5ef8dab3c0a01cc/evaluation/image_eval.py#L144).

Can you change the line to:

`gt_caption = list(caption_dict[gt_img_name].items())[1][1]
`

Right now it throws an error because the input is both the pre-edit and post-edit global description.

**Comment by drogozhang** [comment]
Hi Benno,

Thanks for pointing it out, I will have a look with the modified code on my side later. If it works on my side I will update it as soon as possible!

Best,
Kai

**Comment by drogozhang** [comment]
Hi Benno,

I think we should use local caption for evaluation so I guess the original code is correct for the local caption (I submitted an old version of the markdown). Please try to follow the updated evaluation README.md and let me know if this issue still happens!

Best,
Kai

**Comment by drogozhang** [comment]
Close for inactivity, let me know if you have any other questions.
