### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by yisol** [OSU-NLP-Group/MagicBrush#16]
Thank you for your great work!
I have a question on the training.
I found that you fine-tuned the instructpix2pix with the magicbrush dataset.
Did you also tryfine-tuning the pre-trained stablediffusion (v1.5 or whatever) with the magicbrush dataset?
If so, how was the performance comparing to the one fine-tuned on instructpix2pix?

**Comment by drogozhang** [comment]
Hi, thanks for the question.

Training stable diffusion with magicbrush leads sub-optimal models. Models can not successfully learn editing task with this amount of data.

**Comment by drogozhang** [comment]
Close for inactivity for now, feel free to re-open/reply if you have any questions.
