### ISSUE TITLE
Image to parquate file

### ISSUE THREAD

**Issue by zengbohan0217** [OSU-NLP-Group/MagicBrush#18]
I try to load the image file into the parquate file, but I meet some problem, I try the following way and fail.

def obtain_base64image(image_path):
    image = Image.open(image_path)

    buffered = io.BytesIO()
    image.save(buffered, format="png")
    img_byte = buffered.getvalue()

    img_base64 = base64.b64encode(img_byte)
    return img_base64

how do you load the image in to the parquet file?

**Comment by drogozhang** [comment]
This is the file I followed to upload local files to huggingface https://github.com/sayakpaul/instruct-pix2pix-dataset

Hope it helps.
