### ISSUE TITLE
Train InstructPix2Pix using MagicBrush dataset

### ISSUE THREAD

**Issue by bimsarapathiraja** [OSU-NLP-Group/MagicBrush#19]
I would really appreciate it if you could list down all the necessary commands and instructions to train instructpix2pix using MagicBrush dataset including starting from installing the dataset.

I know I can use the huggingface dataset using datasets library but I'm not clear how to use that with the instructpix2pix code.

**Comment by drogozhang** [comment]
The [finetune_configruation](https://github.com/OSU-NLP-Group/MagicBrush/blob/main/finetune.yaml) lists all the details for fine-tuning.

You can also access the original files for training and evaluation.
[train.zip](https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/zhang_13253_buckeyemail_osu_edu/EYEqf_yG36lAgiXw2GvRl0QBDBOeZHxvNgxO0Ec9WDMcNg?e=6unjPp)

[val.zip](https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/zhang_13253_buckeyemail_osu_edu/EeUPe0U5o_ZAs57tByopB04B8pFFjaeTBmNg6qE9fMQOYg?e=ftItDG)

I don't quite remember if this is the needed format for IP2P training but It should be extremely simple to convert to IP2P format even if necessary.

**Comment by bimsarapathiraja** [comment]
I tried to convert your data into ip2p format. Could you upload that code too. I would really appreciate it if you could add step by step commands if possible.

**Comment by drogozhang** [comment]
I don't have the source code anymore.
But I think the current data format only needs very minimal edits (likely within 30mins) on the IP2P loading func for running.

**Comment by bimsarapathiraja** [comment]
Hi I believe I fixed the dataset problem. Can you show me which code part decide the total no of epochs or steps the code is going to run? Is it in the finetune.yaml file or in the main.py file in the instructpix2pix?

**Comment by drogozhang** [comment]
finetune.yaml
select the best checkpoint based on manual eval on the dev set

**Comment by bimsarapathiraja** [comment]
Thank you for quick response. Could you tell me how you specify the total no of epochs/ steps in the finetune.yaml file?

**Comment by drogozhang** [comment]
![IMG_4217](https://github.com/user-attachments/assets/3971c222-5375-4a54-a26b-302906b685be)

This is in our paper
