### ISSUE TITLE
Training on only MagicBrush

### ISSUE THREAD

**Issue by vidit98** [OSU-NLP-Group/MagicBrush#2]
Hi, thanks for the great work! Have you tried training the model only on MagicBrush data and not using Instructpix2pix data? It would be really interesting to see how does it perform

**Comment by drogozhang** [comment]
Hi @vidit98 , Thanks for your interest!
We haven't tried to train the diffusion model only on MagicBrush as generally instruct-guided models perform better from more paired data, as shown in HIVE https://arxiv.org/abs/2303.09618.
But as stronger original checkpoints come out, we plan to have a try!
