### ISSUE TITLE
Can you provide code edit_cli.py and edit_app.py?

### ISSUE THREAD

**Issue by cc13qq** [OSU-NLP-Group/MagicBrush#20]

**Comment by drogozhang** [comment]
It's already there https://github.com/OSU-NLP-Group/MagicBrush/blob/main/edit_cli_single_multi_turn.py

**Comment by cc13qq** [comment]
> It's already there https://github.com/OSU-NLP-Group/MagicBrush/blob/main/edit_cli_single_multi_turn.py

What about configs/generate.yaml and edit_sessions.json? I cannot find it.

**Comment by drogozhang** [comment]
https://github.com/timothybrooks/instruct-pix2pix/blob/main/configs/generate.yaml
