### ISSUE TITLE
about testset

### ISSUE THREAD

**Issue by llllly26** [OSU-NLP-Group/MagicBrush#24]
Hi, thanks for your great work!

I have some confusion.
1.  I want to learn the detailed definition of four JSON files in the test dataset, including `edit_session.json`, `local_descriptions.json`, `global_descriptions.json` , `edit_turns.json`.  For example,   (a). In the `edit_turn.json` and `edit_sessions.json`, I find that the instruction is basically the same(right? I just sample some to check). Does this mean that I can test instructions by loading any file? (b). In the `global_descriptions.json` and `local_descriptions.json`, the same output has different caption. For instance,  In `global_descriptions.json`, one case is:
```
    "368667": {
        "368667-input.png": "A couple of horses in a field at a ranch.",
        "368667-output1.png": "Horses grazing by a stream at a ranch.",
        "368667-output2.png": "Horses grazing by a stream at a ranch with a giraffe in the field.",
        "368667-output3.png": "Horses grazing by a stream at a ranch with a giraffe in the field under a supernova explosion in the sky."
    }
```
but in the `local_descriptions.json`, it change to:
```
    "368667": {
        "368667-output1.png": "field with stream and horses",
        "368667-output2.png": "giraffe and horses grazing by a stream at a ranch.",
        "368667-output3.png": "supernova explosion in the sky"
    }
```
how to understand the different caption description in different json file? What is the difference when using them?
2.  I find that there are several editing types, how can I load different test set with the annotation editing type?

thanks!

**Comment by drogozhang** [comment]
Hi, 
Thanks for your interest in our work.
for (1) As some baselines do not accept instruction-format as text input for image editing. Instead, some of them may need full **caption** of the **entire** target image (so global caption) and another of them need **caption** of the edited **region** (not the entire target image but only the caption of the masked region, so local caption).

For instruction-guided image editing models like IP2P and MagicBrush, simply use `edit_turns` or `edit_sessions` would be file.
`edit_turn` and `edit_session` are the same instructions used in different editing scenarios (single-turn and multi-turn).

**Please refer to our paper for more details.**


I don't get question 2 but I think you can just follow the README and get the our results. For baselines, please refer to their repos correspondingly.
