### ISSUE TITLE
Mask-provided editing

### ISSUE THREAD

**Issue by ChongjianGE** [OSU-NLP-Group/MagicBrush#6]
Thanks for the great work. 
Kindly ask that is there any plan to release the code and trained models for mask-provided editing demo?

**Comment by drogozhang** [comment]
Hi,

Thanks for your interest!

For mask-provided baselines ([Blended Diffusion](https://github.com/omriav/blended-diffusion) and [GLIDE](https://github.com/openai/glide-text2im)), we used off-the-shelf checkpoints for experiments. You can get the code and trained models via the link.

If you're referring to the trained [InstructPix2Pix](https://github.com/timothybrooks/instruct-pix2pix) for the mask-provided editing setting, we don't have any plans for it at the moment. But we will inform you if we decide to pursue it in the future :)

Best,
Kai
