### ISSUE TITLE
Multi-turn inference code?

### ISSUE THREAD

**Issue by yuzhou914** [OSU-NLP-Group/MagicBrush#7]
Thank you very much for that great work, and I wonder if you can release the single-turn and multi-turn inference code?

**Comment by drogozhang** [comment]
Hi, thanks for your kind words! 

We have just uploaded the inference script named `edit_cli_single_multi_turn.py`. Please note that it was designed to be used with the dataset format we shared in the OneDrive link. We plan to add support for the Huggingface dataset format in the future.

Let me know if you have any other questions.

**Comment by yuzhou914** [comment]
Yes, thank you very much for your update.
