### ISSUE TITLE
Diffusers checkpoint?

### ISSUE THREAD

**Issue by yuzhou914** [OSU-NLP-Group/MagicBrush#8]
Thank you very much for your great work! I just wonder if you have the checkpoint that can be loaded by diffusers, or can your ldm checkpoint be converted into diffusers one? Thank you for your attention.

**Comment by drogozhang** [comment]
Hi,

Thanks for your interest, please check these: [MagicBrush-Paper](https://huggingface.co/vinesmsuic/magicbrush-paper) and [MagicBrush-Jul17](https://huggingface.co/vinesmsuic/magicbrush-jul7)

And we have also updated the README with these links, please let me know if you have any further questions.

Best,
Kai

**Comment by yuzhou914** [comment]
Yes, thank you very much for your reply. There is another thing I wonder, when I use your checkpoint MagicBrush-epoch-52-step-4999.ckpt, and inference all the 535 test samples of the MagicBrush, and I use your evaluation code to test the metrics. However, I found that the metrics cannot match your paper Table-2.
For example, when I use image_eval.py to compute the metrics for all single-turn images, I can only get:
# Evaluation for MagicBrush ckpt...
# 1. MB: single-turn L1 distance: 0.08002114621701262
# 2. MB: single-turn L2 distance: 0.02802231383207232
# 3. MB: single-turn CLIP-I: 0.8978241640165208
# 4. MB: single-turn CLIP-T: 0.29793981013418036 + 4. MB: single-turn CLIP-T Oracle: 0.3068954378564586
# 5. MB: single-turn DINO: 0.7901877011159206
Maybe there is some gap between the evaluation result I get comparing with your paper Table-2. I wonder if there is some other test-time augmentation or tricks for that, how can I align your result with your paper by the MagicBrush ckpt? Thank you very much for your attention.

**Comment by drogozhang** [comment]
Hi, 

Thanks for your interest, we use `MagicBrush-epoch-000168.ckpt` in paper. 
Note that although we believe `MagicBrush-epoch-52-step-4999.ckpt` found recently is better at generation (based on manual checking on the dev set), its quantitative evaluation is a bit worse than the checkpoint in paper (168.ckpt).

Best,
Kai
